server:
  port: 8080

spring:
  jpa:
    database: h2
    show-sql: true
    properties:
      hibernate.format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/./snack-ex;MODE=MySQL;
    username: SA

  sql:
    init:
      mode: always